from .userSerializer import UserSerializer
from .roleSerializer import RoleSerializer
from .serieSerializer import SerieSerializer
from .subserieSerializer import SubserieSerializer
from .dependenciaSerializer import DependenciaSerializer
from .contratoSerializer import ContratoSerializer
from .documentoSerializer import DocumentoSerializer
from .historicoSerializer import HistoricoSerializer
from .reporteSerializer import ReporteSerializer
from .servidorSerializer import ServidorSerializer
