from .user import User
from .role import Role
from .serie import Serie
from .subserie import Subserie
from .dependencia import Dependencia
from .contrato import Contrato
from .documento import Documento
from .historico import Historico
from .reporte import Reporte
from .servidor import Servidor
